"""Initialize comment."""
# Form implementation generated from reading ui file 'src/forms/item.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class ItemForm(object):
    """Initialize comment."""

    def __init__(self, ItemForm):
        """Initialize comment."""
        self.setupUi(ItemForm)

    def setupUi(self, ItemForm):
        """Initialize comment."""
        ItemForm.setObjectName("ItemForm")
        ItemForm.resize(910, 580)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ItemForm.sizePolicy().hasHeightForWidth())
        ItemForm.setSizePolicy(sizePolicy)
        ItemForm.setStyleSheet("")
        ItemForm.setSizeGripEnabled(False)
        ItemForm.setModal(False)
        self.group_4 = QtWidgets.QGroupBox(parent=ItemForm)
        self.group_4.setGeometry(QtCore.QRect(10, 525, 890, 51))
        self.group_4.setAutoFillBackground(True)
        self.group_4.setTitle("")
        self.group_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.group_4.setFlat(False)
        self.group_4.setObjectName("group_4")
        self.cancel_button = QtWidgets.QPushButton(parent=self.group_4)
        self.cancel_button.setGeometry(QtCore.QRect(560, 10, 100, 36))
        self.cancel_button.setObjectName("cancel_button")
        self.save_new_button = QtWidgets.QPushButton(parent=self.group_4)
        self.save_new_button.setGeometry(QtCore.QRect(670, 10, 100, 36))
        self.save_new_button.setObjectName("save_new_button")
        self.save_done_button = QtWidgets.QPushButton(parent=self.group_4)
        self.save_done_button.setGeometry(QtCore.QRect(780, 10, 100, 36))
        self.save_done_button.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.save_done_button.setAutoFillBackground(False)
        self.save_done_button.setFlat(False)
        self.save_done_button.setObjectName("save_done_button")
        self.delete_button = QtWidgets.QPushButton(parent=self.group_4)
        self.delete_button.setGeometry(QtCore.QRect(10, 10, 100, 36))
        self.delete_button.setObjectName("delete_button")
        self.group_3 = QtWidgets.QGroupBox(parent=ItemForm)
        self.group_3.setGeometry(QtCore.QRect(10, 315, 890, 210))
        self.group_3.setFlat(False)
        self.group_3.setObjectName("group_3")
        self.order_table = QtWidgets.QTableWidget(parent=self.group_3)
        self.order_table.setGeometry(QtCore.QRect(10, 30, 870, 170))
        self.order_table.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.order_table.setAlternatingRowColors(True)
        self.order_table.setObjectName("order_table")
        self.order_table.setColumnCount(0)
        self.order_table.setRowCount(0)
        self.order_table.verticalHeader().setVisible(False)
        self.group_1 = QtWidgets.QGroupBox(parent=ItemForm)
        self.group_1.setGeometry(QtCore.QRect(10, 5, 431, 305))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_1.sizePolicy().hasHeightForWidth())
        self.group_1.setSizePolicy(sizePolicy)
        self.group_1.setAutoFillBackground(True)
        self.group_1.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.group_1.setFlat(False)
        self.group_1.setObjectName("group_1")
        self.entry_index_label = QtWidgets.QLabel(parent=self.group_1)
        self.entry_index_label.setGeometry(QtCore.QRect(5, 30, 125, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.entry_index_label.sizePolicy().hasHeightForWidth()
        )
        self.entry_index_label.setSizePolicy(sizePolicy)
        self.entry_index_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.entry_index_label.setObjectName("entry_index_label")
        self.assembly_label = QtWidgets.QLabel(parent=self.group_1)
        self.assembly_label.setGeometry(QtCore.QRect(5, 70, 125, 36))
        self.assembly_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.assembly_label.setObjectName("assembly_label")
        self.condition_label = QtWidgets.QLabel(parent=self.group_1)
        self.condition_label.setGeometry(QtCore.QRect(5, 110, 125, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.condition_label.sizePolicy().hasHeightForWidth()
        )
        self.condition_label.setSizePolicy(sizePolicy)
        self.condition_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.condition_label.setObjectName("condition_label")
        self.quantity_label = QtWidgets.QLabel(parent=self.group_1)
        self.quantity_label.setGeometry(QtCore.QRect(5, 150, 125, 30))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.quantity_label.sizePolicy().hasHeightForWidth()
        )
        self.quantity_label.setSizePolicy(sizePolicy)
        self.quantity_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.quantity_label.setObjectName("quantity_label")
        self.record_id_combo = QtWidgets.QComboBox(parent=self.group_1)
        self.record_id_combo.setGeometry(QtCore.QRect(140, 30, 161, 36))
        self.record_id_combo.setObjectName("record_id_combo")
        self.assembly_edit = QtWidgets.QLineEdit(parent=self.group_1)
        self.assembly_edit.setGeometry(QtCore.QRect(140, 70, 126, 36))
        self.assembly_edit.setPlaceholderText("")
        self.assembly_edit.setObjectName("assembly_edit")
        self.condition_combo = QtWidgets.QComboBox(parent=self.group_1)
        self.condition_combo.setGeometry(QtCore.QRect(140, 110, 126, 36))
        self.condition_combo.setObjectName("condition_combo")
        self.quantity_edit = QtWidgets.QLineEdit(parent=self.group_1)
        self.quantity_edit.setGeometry(QtCore.QRect(140, 150, 91, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.quantity_edit.sizePolicy().hasHeightForWidth()
        )
        self.quantity_edit.setSizePolicy(sizePolicy)
        self.quantity_edit.setObjectName("quantity_edit")
        self.installed_label = QtWidgets.QLabel(parent=self.group_1)
        self.installed_label.setGeometry(QtCore.QRect(5, 190, 125, 25))
        self.installed_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.installed_label.setObjectName("installed_label")
        self.installed_chkbox = QtWidgets.QCheckBox(parent=self.group_1)
        self.installed_chkbox.setGeometry(QtCore.QRect(140, 190, 97, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.installed_chkbox.sizePolicy().hasHeightForWidth()
        )
        self.installed_chkbox.setSizePolicy(sizePolicy)
        self.installed_chkbox.setText("")
        self.installed_chkbox.setObjectName("installed_chkbox")
        self.storage_box_label = QtWidgets.QLabel(parent=self.group_1)
        self.storage_box_label.setGeometry(QtCore.QRect(5, 220, 125, 37))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.storage_box_label.sizePolicy().hasHeightForWidth()
        )
        self.storage_box_label.setSizePolicy(sizePolicy)
        self.storage_box_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.storage_box_label.setObjectName("storage_box_label")
        self.storage_box_edit = QtWidgets.QLineEdit(parent=self.group_1)
        self.storage_box_edit.setGeometry(QtCore.QRect(140, 220, 80, 36))
        self.storage_box_edit.setObjectName("storage_box_edit")
        self.remarks_label = QtWidgets.QLabel(parent=self.group_1)
        self.remarks_label.setGeometry(QtCore.QRect(5, 260, 125, 37))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.remarks_label.sizePolicy().hasHeightForWidth()
        )
        self.remarks_label.setSizePolicy(sizePolicy)
        self.remarks_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.remarks_label.setObjectName("remarks_label")
        self.remarks_edit = QtWidgets.QLineEdit(parent=self.group_1)
        self.remarks_edit.setGeometry(QtCore.QRect(140, 260, 271, 37))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarks_edit.sizePolicy().hasHeightForWidth())
        self.remarks_edit.setSizePolicy(sizePolicy)
        self.remarks_edit.setObjectName("remarks_edit")
        self.group_2 = QtWidgets.QGroupBox(parent=ItemForm)
        self.group_2.setGeometry(QtCore.QRect(480, 5, 420, 281))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_2.sizePolicy().hasHeightForWidth())
        self.group_2.setSizePolicy(sizePolicy)
        self.group_2.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.group_2.setFlat(True)
        self.group_2.setObjectName("group_2")
        self.part_number_label = QtWidgets.QLabel(parent=self.group_2)
        self.part_number_label.setGeometry(QtCore.QRect(5, 30, 150, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.part_number_label.sizePolicy().hasHeightForWidth()
        )
        self.part_number_label.setSizePolicy(sizePolicy)
        self.part_number_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.part_number_label.setObjectName("part_number_label")
        self.source_label = QtWidgets.QLabel(parent=self.group_2)
        self.source_label.setGeometry(QtCore.QRect(5, 70, 150, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_label.sizePolicy().hasHeightForWidth())
        self.source_label.setSizePolicy(sizePolicy)
        self.source_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.source_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.source_label.setObjectName("source_label")
        self.description_label = QtWidgets.QLabel(parent=self.group_2)
        self.description_label.setGeometry(QtCore.QRect(5, 110, 150, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.description_label.sizePolicy().hasHeightForWidth()
        )
        self.description_label.setSizePolicy(sizePolicy)
        self.description_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.description_label.setObjectName("description_label")
        self.part_remarks_label = QtWidgets.QLabel(parent=self.group_2)
        self.part_remarks_label.setGeometry(QtCore.QRect(5, 150, 150, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.part_remarks_label.sizePolicy().hasHeightForWidth()
        )
        self.part_remarks_label.setSizePolicy(sizePolicy)
        self.part_remarks_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.part_remarks_label.setObjectName("part_remarks_label")
        self.total_qty_label = QtWidgets.QLabel(parent=self.group_2)
        self.total_qty_label.setGeometry(QtCore.QRect(5, 190, 150, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.total_qty_label.sizePolicy().hasHeightForWidth()
        )
        self.total_qty_label.setSizePolicy(sizePolicy)
        self.total_qty_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.total_qty_label.setObjectName("total_qty_label")
        self.part_number_combo = QtWidgets.QComboBox(parent=self.group_2)
        self.part_number_combo.setGeometry(QtCore.QRect(170, 30, 235, 37))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.part_number_combo.sizePolicy().hasHeightForWidth()
        )
        self.part_number_combo.setSizePolicy(sizePolicy)
        self.part_number_combo.setMaxVisibleItems(20)
        self.part_number_combo.setObjectName("part_number_combo")
        self.source_text = QtWidgets.QLabel(parent=self.group_2)
        self.source_text.setGeometry(QtCore.QRect(170, 70, 235, 35))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_text.sizePolicy().hasHeightForWidth())
        self.source_text.setSizePolicy(sizePolicy)
        self.source_text.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.source_text.setText("")
        self.source_text.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.source_text.setObjectName("source_text")
        self.description_text = QtWidgets.QLabel(parent=self.group_2)
        self.description_text.setGeometry(QtCore.QRect(170, 110, 235, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.description_text.sizePolicy().hasHeightForWidth()
        )
        self.description_text.setSizePolicy(sizePolicy)
        self.description_text.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.description_text.setText("")
        self.description_text.setWordWrap(True)
        self.description_text.setObjectName("description_text")
        self.remarks_text = QtWidgets.QLabel(parent=self.group_2)
        self.remarks_text.setGeometry(QtCore.QRect(170, 150, 235, 36))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarks_text.sizePolicy().hasHeightForWidth())
        self.remarks_text.setSizePolicy(sizePolicy)
        self.remarks_text.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.remarks_text.setText("")
        self.remarks_text.setWordWrap(True)
        self.remarks_text.setObjectName("remarks_text")
        self.total_qty_text = QtWidgets.QLabel(parent=self.group_2)
        self.total_qty_text.setGeometry(QtCore.QRect(170, 190, 235, 41))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.total_qty_text.sizePolicy().hasHeightForWidth()
        )
        self.total_qty_text.setSizePolicy(sizePolicy)
        self.total_qty_text.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.total_qty_text.setText("")
        self.total_qty_text.setObjectName("total_qty_text")

        self.retranslateUi(ItemForm)
        QtCore.QMetaObject.connectSlotsByName(ItemForm)
        ItemForm.setTabOrder(self.record_id_combo, self.assembly_edit)
        ItemForm.setTabOrder(self.assembly_edit, self.condition_combo)
        ItemForm.setTabOrder(self.condition_combo, self.quantity_edit)
        ItemForm.setTabOrder(self.quantity_edit, self.installed_chkbox)
        ItemForm.setTabOrder(self.installed_chkbox, self.storage_box_edit)
        ItemForm.setTabOrder(self.storage_box_edit, self.remarks_edit)
        ItemForm.setTabOrder(self.remarks_edit, self.delete_button)
        ItemForm.setTabOrder(self.delete_button, self.cancel_button)
        ItemForm.setTabOrder(self.cancel_button, self.save_new_button)
        ItemForm.setTabOrder(self.save_new_button, self.save_done_button)

    def retranslateUi(self, ItemForm):
        """Initialize comment."""
        _translate = QtCore.QCoreApplication.translate
        ItemForm.setWindowTitle(_translate("ItemForm", "Edit an Item"))
        self.cancel_button.setToolTip(
            _translate(
                "ItemForm", "Close the form, optionally saving any changed information"
            )
        )
        self.cancel_button.setText(_translate("ItemForm", "Cancel"))
        self.save_new_button.setToolTip(
            _translate("ItemForm", "Save the current item, then clear the form")
        )
        self.save_new_button.setText(_translate("ItemForm", "Save / New"))
        self.save_done_button.setToolTip(
            _translate("ItemForm", "Save the current item, then close the form")
        )
        self.save_done_button.setText(_translate("ItemForm", "Save / Done"))
        self.delete_button.setToolTip(
            _translate(
                "ItemForm",
                "Permanently DELETE the current item and all the order lines",
            )
        )
        self.delete_button.setText(_translate("ItemForm", "Delete Item"))
        self.group_3.setTitle(_translate("ItemForm", "Item Orders"))
        self.order_table.setSortingEnabled(False)
        self.group_1.setTitle(_translate("ItemForm", "Item Info"))
        self.entry_index_label.setToolTip(
            _translate("ItemForm", "Required: Select the Item index.")
        )
        self.entry_index_label.setText(_translate("ItemForm", "Item ID Number:"))
        self.assembly_label.setText(_translate("ItemForm", "Assembly:"))
        self.condition_label.setText(_translate("ItemForm", "Condition:"))
        self.quantity_label.setText(_translate("ItemForm", "Quantity Required:"))
        self.record_id_combo.setToolTip(
            _translate("ItemForm", "Required: Select the Item index")
        )
        self.record_id_combo.setPlaceholderText(
            _translate("ItemForm", "To Be Assigned")
        )
        self.assembly_edit.setToolTip(
            _translate("ItemForm", "Required: Enter the Assembly, 1 to 15 Characters")
        )
        self.assembly_edit.setWhatsThis(
            _translate("ItemForm", "Required: Enter the Assembly, 1 to 15 Characters")
        )
        self.condition_combo.setWhatsThis(
            _translate("ItemForm", "Required: Select the Item Condition")
        )
        self.quantity_edit.setToolTip(
            _translate("ItemForm", "Required: Enter quantity, 0 to  999, 0 defaul")
        )
        self.installed_label.setText(_translate("ItemForm", "Installed:"))
        self.installed_chkbox.setToolTip(
            _translate("ItemForm", "Check if Item is installed")
        )
        self.storage_box_label.setText(_translate("ItemForm", "Storage Box:"))
        self.storage_box_edit.setToolTip(
            _translate("ItemForm", "Optional: Enter Storage box if stored, 0 to 99")
        )
        self.remarks_label.setText(_translate("ItemForm", "Remarks:"))
        self.remarks_edit.setToolTip(
            _translate("ItemForm", "Optional: up to 255 characters")
        )
        self.group_2.setTitle(_translate("ItemForm", "Part Info"))
        self.part_number_label.setText(_translate("ItemForm", "Part Number:"))
        self.source_label.setText(_translate("ItemForm", "Part Source:"))
        self.description_label.setText(_translate("ItemForm", "Description:"))
        self.part_remarks_label.setText(_translate("ItemForm", "Parts Remarks:"))
        self.total_qty_label.setText(_translate("ItemForm", "Total Quantity In Car:"))
        self.part_number_combo.setToolTip(
            _translate("ItemForm", "Select Part Number, Required")
        )
