"""Initialize comment."""
# Form implementation generated from reading ui file 'src/forms/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class PartsTracker(object):
    """Initialize comment."""

    def __init__(self, PartsTracker):
        """Initialize comment."""
        self.setupUi(PartsTracker)

    def setupUi(self, PartsTracker):
        """Initialize comment."""
        PartsTracker.setObjectName("PartsTracker")
        PartsTracker.resize(1237, 908)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PartsTracker.sizePolicy().hasHeightForWidth())
        PartsTracker.setSizePolicy(sizePolicy)
        PartsTracker.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=PartsTracker)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centralwidget.sizePolicy().hasHeightForWidth()
        )
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 1241, 881))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_widget = QtWidgets.QTabWidget(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.tab_widget.setObjectName("tab_widget")
        self.asssembly_listing = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.asssembly_listing.sizePolicy().hasHeightForWidth()
        )
        self.asssembly_listing.setSizePolicy(sizePolicy)
        self.asssembly_listing.setObjectName("asssembly_listing")
        self.frame = QtWidgets.QFrame(parent=self.asssembly_listing)
        self.frame.setGeometry(QtCore.QRect(0, -1, 241, 51))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.button_expand_tree = QtWidgets.QPushButton(parent=self.frame)
        self.button_expand_tree.setGeometry(QtCore.QRect(0, 10, 115, 36))
        self.button_expand_tree.setObjectName("button_expand_tree")
        self.button_collapse_tree = QtWidgets.QPushButton(parent=self.frame)
        self.button_collapse_tree.setGeometry(QtCore.QRect(120, 10, 115, 36))
        self.button_collapse_tree.setObjectName("button_collapse_tree")
        self.assembly_tree_widget = QtWidgets.QTreeWidget(parent=self.asssembly_listing)
        self.assembly_tree_widget.setGeometry(QtCore.QRect(0, 60, 1222, 817))
        self.assembly_tree_widget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.assembly_tree_widget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.assembly_tree_widget.setLineWidth(0)
        self.assembly_tree_widget.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn
        )
        self.assembly_tree_widget.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow
        )
        self.assembly_tree_widget.setColumnCount(8)
        self.assembly_tree_widget.setObjectName("assembly_tree_widget")
        self.assembly_tree_widget.headerItem().setText(0, "1")
        self.assembly_tree_widget.headerItem().setText(1, "2")
        self.assembly_tree_widget.headerItem().setText(2, "3")
        self.assembly_tree_widget.headerItem().setText(3, "4")
        self.assembly_tree_widget.headerItem().setText(4, "5")
        self.assembly_tree_widget.headerItem().setText(5, "6")
        self.assembly_tree_widget.headerItem().setText(6, "7")
        self.assembly_tree_widget.headerItem().setText(7, "8")
        self.tab_widget.addTab(self.asssembly_listing, "")
        self.parts_list = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parts_list.sizePolicy().hasHeightForWidth())
        self.parts_list.setSizePolicy(sizePolicy)
        self.parts_list.setObjectName("parts_list")
        self.parts_table_widget = QtWidgets.QTableWidget(parent=self.parts_list)
        self.parts_table_widget.setGeometry(QtCore.QRect(0, 0, 1222, 817))
        self.parts_table_widget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.parts_table_widget.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded
        )
        self.parts_table_widget.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded
        )
        self.parts_table_widget.setGridStyle(QtCore.Qt.PenStyle.DotLine)
        self.parts_table_widget.setObjectName("parts_table_widget")
        self.parts_table_widget.setColumnCount(0)
        self.parts_table_widget.setRowCount(0)
        self.parts_table_widget.verticalHeader().setVisible(False)
        self.tab_widget.addTab(self.parts_list, "")
        self.orders_list = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orders_list.sizePolicy().hasHeightForWidth())
        self.orders_list.setSizePolicy(sizePolicy)
        self.orders_list.setObjectName("orders_list")
        self.orders_table_widget = QtWidgets.QTableWidget(parent=self.orders_list)
        self.orders_table_widget.setGeometry(QtCore.QRect(0, 0, 1222, 817))
        self.orders_table_widget.setGridStyle(QtCore.Qt.PenStyle.DotLine)
        self.orders_table_widget.setObjectName("orders_table_widget")
        self.orders_table_widget.setColumnCount(0)
        self.orders_table_widget.setRowCount(0)
        self.orders_table_widget.horizontalHeader().setSortIndicatorShown(True)
        self.orders_table_widget.verticalHeader().setVisible(False)
        self.tab_widget.addTab(self.orders_list, "")
        self.horizontalLayout.addWidget(self.tab_widget)
        PartsTracker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PartsTracker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1237, 29))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menu_assembly_listing = QtWidgets.QMenu(parent=self.menubar)
        self.menu_assembly_listing.setObjectName("menu_assembly_listing")
        self.menu_parts = QtWidgets.QMenu(parent=self.menubar)
        self.menu_parts.setObjectName("menu_parts")
        self.menu_orders = QtWidgets.QMenu(parent=self.menubar)
        self.menu_orders.setObjectName("menu_orders")
        self.menu_file = QtWidgets.QMenu(parent=self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_file_recent = QtWidgets.QMenu(parent=self.menu_file)
        self.menu_file_recent.setObjectName("menu_file_recent")
        self.menu_help = QtWidgets.QMenu(parent=self.menubar)
        self.menu_help.setObjectName("menu_help")
        PartsTracker.setMenuBar(self.menubar)
        self.action_update_assemby_tree = QtGui.QAction(parent=PartsTracker)
        self.action_update_assemby_tree.setObjectName("action_update_assemby_tree")
        self.action_save_assembly_list = QtGui.QAction(parent=PartsTracker)
        self.action_save_assembly_list.setObjectName("action_save_assembly_list")
        self.actionSave = QtGui.QAction(parent=PartsTracker)
        self.actionSave.setObjectName("actionSave")
        self.action_edit_item = QtGui.QAction(parent=PartsTracker)
        self.action_edit_item.setObjectName("action_edit_item")
        self.action_new_item = QtGui.QAction(parent=PartsTracker)
        self.action_new_item.setObjectName("action_new_item")
        self.ActionItemDelete = QtGui.QAction(parent=PartsTracker)
        self.ActionItemDelete.setObjectName("ActionItemDelete")
        self.action_edit_assembly_tree = QtGui.QAction(parent=PartsTracker)
        self.action_edit_assembly_tree.setObjectName("action_edit_assembly_tree")
        self.action_update_part_list_table = QtGui.QAction(parent=PartsTracker)
        self.action_update_part_list_table.setObjectName(
            "action_update_part_list_table"
        )
        self.action_edit_part = QtGui.QAction(parent=PartsTracker)
        self.action_edit_part.setObjectName("action_edit_part")
        self.action_new_part = QtGui.QAction(parent=PartsTracker)
        self.action_new_part.setObjectName("action_new_part")
        self.ActionPartDelete = QtGui.QAction(parent=PartsTracker)
        self.ActionPartDelete.setObjectName("ActionPartDelete")
        self.action_change_part_number = QtGui.QAction(parent=PartsTracker)
        self.action_change_part_number.setObjectName("action_change_part_number")
        self.action_update_order_table = QtGui.QAction(parent=PartsTracker)
        self.action_update_order_table.setObjectName("action_update_order_table")
        self.action_edit_order = QtGui.QAction(parent=PartsTracker)
        self.action_edit_order.setObjectName("action_edit_order")
        self.action_new_order = QtGui.QAction(parent=PartsTracker)
        self.action_new_order.setObjectName("action_new_order")
        self.ActionOrderDelete = QtGui.QAction(parent=PartsTracker)
        self.ActionOrderDelete.setObjectName("ActionOrderDelete")
        self.action_file_open = QtGui.QAction(parent=PartsTracker)
        self.action_file_open.setMenuRole(QtGui.QAction.MenuRole.TextHeuristicRole)
        self.action_file_open.setObjectName("action_file_open")
        self.action_file_close = QtGui.QAction(parent=PartsTracker)
        self.action_file_close.setObjectName("action_file_close")
        self.action_recent_file_1 = QtGui.QAction(parent=PartsTracker)
        self.action_recent_file_1.setObjectName("action_recent_file_1")
        self.action_recent_file_2 = QtGui.QAction(parent=PartsTracker)
        self.action_recent_file_2.setObjectName("action_recent_file_2")
        self.action_recent_file_3 = QtGui.QAction(parent=PartsTracker)
        self.action_recent_file_3.setObjectName("action_recent_file_3")
        self.action_recent_file_4 = QtGui.QAction(parent=PartsTracker)
        self.action_recent_file_4.setObjectName("action_recent_file_4")
        self.action_file_exit = QtGui.QAction(parent=PartsTracker)
        self.action_file_exit.setObjectName("action_file_exit")
        self.action_file_new = QtGui.QAction(parent=PartsTracker)
        self.action_file_new.setObjectName("action_file_new")
        self.action_edit_conditions = QtGui.QAction(parent=PartsTracker)
        self.action_edit_conditions.setObjectName("action_edit_conditions")
        self.action_update_sources = QtGui.QAction(parent=PartsTracker)
        self.action_update_sources.setObjectName("action_update_sources")
        self.menu_assembly_listing.addAction(self.action_new_item)
        self.menu_assembly_listing.addAction(self.action_edit_item)
        self.menu_assembly_listing.addAction(self.action_edit_conditions)
        self.menu_assembly_listing.addSeparator()
        self.menu_assembly_listing.addAction(self.action_edit_assembly_tree)
        self.menu_assembly_listing.addAction(self.action_save_assembly_list)
        self.menu_assembly_listing.addSeparator()
        self.menu_assembly_listing.addAction(self.action_update_assemby_tree)
        self.menu_parts.addAction(self.action_new_part)
        self.menu_parts.addAction(self.action_edit_part)
        self.menu_parts.addAction(self.action_update_sources)
        self.menu_parts.addSeparator()
        self.menu_parts.addAction(self.action_change_part_number)
        self.menu_parts.addAction(self.action_update_part_list_table)
        self.menu_orders.addAction(self.action_new_order)
        self.menu_orders.addAction(self.action_edit_order)
        self.menu_orders.addSeparator()
        self.menu_orders.addAction(self.action_update_order_table)
        self.menu_file_recent.addAction(self.action_recent_file_1)
        self.menu_file_recent.addAction(self.action_recent_file_2)
        self.menu_file_recent.addAction(self.action_recent_file_3)
        self.menu_file_recent.addAction(self.action_recent_file_4)
        self.menu_file.addAction(self.action_file_open)
        self.menu_file.addAction(self.action_file_close)
        self.menu_file.addAction(self.action_file_new)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.menu_file_recent.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_file_exit)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_assembly_listing.menuAction())
        self.menubar.addAction(self.menu_parts.menuAction())
        self.menubar.addAction(self.menu_orders.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(PartsTracker)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PartsTracker)

    def retranslateUi(self, PartsTracker):
        """Initialize comment."""
        _translate = QtCore.QCoreApplication.translate
        PartsTracker.setWindowTitle(_translate("PartsTracker", "Parts Tracker"))
        self.button_expand_tree.setText(_translate("PartsTracker", "Expand Tree"))
        self.button_collapse_tree.setText(_translate("PartsTracker", "Collapse Tree"))
        self.tab_widget.setTabText(
            self.tab_widget.indexOf(self.asssembly_listing),
            _translate("PartsTracker", "Assembly List"),
        )
        self.parts_table_widget.setSortingEnabled(True)
        self.tab_widget.setTabText(
            self.tab_widget.indexOf(self.parts_list),
            _translate("PartsTracker", "Parts List"),
        )
        self.orders_table_widget.setSortingEnabled(True)
        self.tab_widget.setTabText(
            self.tab_widget.indexOf(self.orders_list),
            _translate("PartsTracker", "Orders List"),
        )
        self.menu_assembly_listing.setTitle(
            _translate("PartsTracker", "Assemblies/Items")
        )
        self.menu_parts.setTitle(_translate("PartsTracker", "Parts"))
        self.menu_orders.setTitle(_translate("PartsTracker", "Orders"))
        self.menu_file.setTitle(_translate("PartsTracker", "File"))
        self.menu_file_recent.setTitle(_translate("PartsTracker", "Recent Files"))
        self.menu_help.setTitle(_translate("PartsTracker", "Help"))
        self.action_update_assemby_tree.setText(
            _translate("PartsTracker", "Update List")
        )
        self.action_save_assembly_list.setText(
            _translate("PartsTracker", "Save Assembly Listing")
        )
        self.actionSave.setText(_translate("PartsTracker", "Save"))
        self.action_edit_item.setText(_translate("PartsTracker", "Edit an Item"))
        self.action_new_item.setText(_translate("PartsTracker", "Add an Item"))
        self.ActionItemDelete.setText(_translate("PartsTracker", "Delete"))
        self.action_edit_assembly_tree.setText(
            _translate("PartsTracker", "Edit Structure")
        )
        self.action_update_part_list_table.setText(
            _translate("PartsTracker", "Update List")
        )
        self.action_edit_part.setText(_translate("PartsTracker", "Edit a Part"))
        self.action_new_part.setText(_translate("PartsTracker", "Add a Part"))
        self.ActionPartDelete.setText(_translate("PartsTracker", "Delete"))
        self.action_change_part_number.setText(
            _translate("PartsTracker", "Change Part Number")
        )
        self.action_update_order_table.setText(
            _translate("PartsTracker", "Update List")
        )
        self.action_edit_order.setText(_translate("PartsTracker", "Edit an Order"))
        self.action_new_order.setText(_translate("PartsTracker", "Add an Order"))
        self.ActionOrderDelete.setText(_translate("PartsTracker", "Delete"))
        self.ActionOrderDelete.setToolTip(
            _translate("PartsTracker", "Delete an Order Completely")
        )
        self.action_file_open.setText(_translate("PartsTracker", "Open Parts File"))
        self.action_file_close.setText(_translate("PartsTracker", "Close Parts File"))
        self.action_recent_file_1.setText(_translate("PartsTracker", "File1"))
        self.action_recent_file_2.setText(_translate("PartsTracker", "File2"))
        self.action_recent_file_3.setText(_translate("PartsTracker", "File3"))
        self.action_recent_file_4.setText(_translate("PartsTracker", "File4"))
        self.action_file_exit.setText(_translate("PartsTracker", "Exit"))
        self.action_file_new.setText(_translate("PartsTracker", "New Parts File"))
        self.action_edit_conditions.setText(
            _translate("PartsTracker", "Edit Available Item Conditions")
        )
        self.action_update_sources.setText(
            _translate("PartsTracker", "Add/Update Part Sources")
        )
