"""Initialize comment."""
# Form implementation generated from reading ui file 'src/forms/part.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from lbk_library import FocusComboBox
from PyQt6 import QtCore, QtWidgets


class PartForm(object):
    """Initialize comment."""

    def __init__(self, PartForm):
        """Initialize comment."""
        self.setupUi(PartForm)

    def setupUi(self, PartForm):
        """Initialize comment."""
        PartForm.setObjectName("PartForm")
        PartForm.resize(910, 626)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PartForm.sizePolicy().hasHeightForWidth())
        PartForm.setSizePolicy(sizePolicy)
        PartForm.setModal(False)
        self.groupBox_1 = QtWidgets.QGroupBox(parent=PartForm)
        self.groupBox_1.setGeometry(QtCore.QRect(10, 5, 435, 261))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_1.sizePolicy().hasHeightForWidth())
        self.groupBox_1.setSizePolicy(sizePolicy)
        self.groupBox_1.setObjectName("groupBox_1")
        self.part_number_label = QtWidgets.QLabel(parent=self.groupBox_1)
        self.part_number_label.setGeometry(QtCore.QRect(5, 30, 100, 36))
        self.part_number_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.part_number_label.setObjectName("part_number_label")
        self.source_label = QtWidgets.QLabel(parent=self.groupBox_1)
        self.source_label.setGeometry(QtCore.QRect(5, 70, 100, 37))
        self.source_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.source_label.setObjectName("source_label")
        self.description_label = QtWidgets.QLabel(parent=self.groupBox_1)
        self.description_label.setGeometry(QtCore.QRect(5, 110, 100, 33))
        self.description_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.description_label.setObjectName("description_label")
        self.remarks_label = QtWidgets.QLabel(parent=self.groupBox_1)
        self.remarks_label.setGeometry(QtCore.QRect(5, 150, 100, 33))
        self.remarks_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.remarks_label.setObjectName("remarks_label")
        self.part_number_combo = FocusComboBox(parent=self.groupBox_1)
        self.part_number_combo.setGeometry(QtCore.QRect(120, 30, 200, 36))
        self.part_number_combo.setObjectName("part_number_combo")
        self.source_combo = FocusComboBox(parent=self.groupBox_1)
        self.source_combo.setGeometry(QtCore.QRect(120, 70, 200, 36))
        self.source_combo.setObjectName("source_combo")
        self.description_edit = QtWidgets.QLineEdit(parent=self.groupBox_1)
        self.description_edit.setGeometry(QtCore.QRect(120, 110, 300, 36))
        self.description_edit.setObjectName("description_edit")
        self.remarks_edit = QtWidgets.QLineEdit(parent=self.groupBox_1)
        self.remarks_edit.setGeometry(QtCore.QRect(120, 150, 300, 36))
        self.remarks_edit.setObjectName("remarks_edit")
        self.record_id_edit = QtWidgets.QLineEdit(parent=self.groupBox_1)
        self.record_id_edit.setGeometry(QtCore.QRect(120, 190, 150, 36))
        self.record_id_edit.setObjectName("record_id_edit")
        self.part_number_edit = QtWidgets.QLineEdit(parent=self.groupBox_1)
        self.part_number_edit.setGeometry(QtCore.QRect(120, 30, 200, 36))
        self.part_number_edit.setObjectName("part_number_edit")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=PartForm)
        self.groupBox_2.setGeometry(QtCore.QRect(445, 5, 420, 330))
        self.groupBox_2.setObjectName("groupBox_2")
        self.item_table = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.item_table.setGeometry(QtCore.QRect(10, 30, 400, 250))
        self.item_table.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.item_table.setObjectName("item_table")
        self.item_table.setColumnCount(0)
        self.item_table.setRowCount(0)
        self.total_qty_text = QtWidgets.QLabel(parent=self.groupBox_2)
        self.total_qty_text.setGeometry(QtCore.QRect(165, 290, 150, 19))
        self.total_qty_text.setObjectName("total_qty_text")
        self.total_qty_label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.total_qty_label.setGeometry(QtCore.QRect(10, 290, 143, 20))
        self.total_qty_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.total_qty_label.setObjectName("total_qty_label")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=PartForm)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 350, 890, 210))
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.order_table = QtWidgets.QTableWidget(parent=self.groupBox_3)
        self.order_table.setGeometry(QtCore.QRect(10, 30, 870, 170))
        self.order_table.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.order_table.setObjectName("order_table")
        self.order_table.setColumnCount(0)
        self.order_table.setRowCount(0)
        self.order_table.verticalHeader().setVisible(False)
        self.order_table.verticalHeader().setHighlightSections(False)
        self.button_bar = QtWidgets.QGroupBox(parent=PartForm)
        self.button_bar.setGeometry(QtCore.QRect(10, 560, 890, 56))
        self.button_bar.setTitle("")
        self.button_bar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.button_bar.setFlat(True)
        self.button_bar.setObjectName("button_bar")
        self.cancel_button = QtWidgets.QPushButton(parent=self.button_bar)
        self.cancel_button.setGeometry(QtCore.QRect(550, 10, 104, 36))
        self.cancel_button.setObjectName("cancel_button")
        self.save_new_button = QtWidgets.QPushButton(parent=self.button_bar)
        self.save_new_button.setGeometry(QtCore.QRect(660, 10, 104, 36))
        self.save_new_button.setObjectName("save_new_button")
        self.save_done_button = QtWidgets.QPushButton(parent=self.button_bar)
        self.save_done_button.setGeometry(QtCore.QRect(770, 10, 104, 36))
        self.save_done_button.setObjectName("save_done_button")
        self.delete_button = QtWidgets.QPushButton(parent=self.button_bar)
        self.delete_button.setGeometry(QtCore.QRect(10, 10, 103, 36))
        self.delete_button.setObjectName("delete_button")

        self.retranslateUi(PartForm)
        QtCore.QMetaObject.connectSlotsByName(PartForm)
        PartForm.setTabOrder(self.part_number_combo, self.part_number_edit)
        PartForm.setTabOrder(self.part_number_edit, self.source_combo)
        PartForm.setTabOrder(self.source_combo, self.description_edit)
        PartForm.setTabOrder(self.description_edit, self.remarks_edit)
        PartForm.setTabOrder(self.remarks_edit, self.record_id_edit)
        PartForm.setTabOrder(self.record_id_edit, self.cancel_button)
        PartForm.setTabOrder(self.cancel_button, self.save_new_button)
        PartForm.setTabOrder(self.save_new_button, self.save_done_button)
        PartForm.setTabOrder(self.save_done_button, self.delete_button)

    def retranslateUi(self, PartForm):
        """Initialize comment."""
        _translate = QtCore.QCoreApplication.translate
        PartForm.setWindowTitle(_translate("PartForm", "Part Editing"))
        self.groupBox_1.setTitle(_translate("PartForm", "Part Info"))
        self.part_number_label.setText(_translate("PartForm", "Part Number"))
        self.source_label.setText(_translate("PartForm", "Source"))
        self.description_label.setText(_translate("PartForm", "Description"))
        self.remarks_label.setText(_translate("PartForm", "Parts Remarks"))
        self.part_number_combo.setToolTip(
            _translate("PartForm", "Select Part Number, Required")
        )
        self.source_combo.setToolTip(
            _translate("PartForm", "Select a Source, Required")
        )
        self.description_edit.setToolTip(
            _translate(
                "PartForm", "Description of the part, Required, up to 255 characters"
            )
        )
        self.remarks_edit.setToolTip(
            _translate(
                "PartForm", "Remarks about this part, Optional, up to 255 characters"
            )
        )
        self.part_number_edit.setToolTip(
            _translate("PartForm", "Select Part Number, Required")
        )
        self.groupBox_2.setTitle(_translate("PartForm", "Item Info"))
        self.total_qty_text.setText(_translate("PartForm", "0"))
        self.total_qty_label.setText(_translate("PartForm", "TeTotal Quantity In Car:"))
        self.groupBox_3.setTitle(_translate("PartForm", "Part Orders"))
        self.cancel_button.setToolTip(
            _translate(
                "PartForm", "Close the form, optionally saving any changed information"
            )
        )
        self.cancel_button.setText(_translate("PartForm", "Cancel"))
        self.save_new_button.setToolTip(
            _translate("PartForm", "Save the current part, then clear the form")
        )
        self.save_new_button.setText(_translate("PartForm", "Save | New"))
        self.save_done_button.setToolTip(
            _translate("PartForm", "Save the current part, then close the form")
        )
        self.save_done_button.setText(_translate("PartForm", "Save | Done"))
        self.delete_button.setToolTip(
            _translate("PartForm", "Permanently Delete the part from the database.")
        )
        self.delete_button.setText(_translate("PartForm", "Delete Part"))
